eureka:
    instance:
        hostname: sagara00325597
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

server:
    port: 8090

spring:
    application:
        name: members
    config:
        import: optional:configserver:http://localhost:8888

    datasource:
        url: jdbc:postgresql://localhost:5432/members
        username: postgres
        password: your_password
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

