version: '3.8'

services:
  member-db:
    image: postgres:15
    container_name: postgres-member
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: members
    volumes:
      - member-data:/var/lib/postgresql/data

  gym-db:
    image: postgres:15
    container_name: postgres-gym
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: gym
    volumes:
      - gym-data:/var/lib/postgresql/data

volumes:
  member-data:
  gym-data:
