version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-single
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      # Set the default database to one of them (here, "members")
      POSTGRES_DB: members
    volumes:
      - db-data:/var/lib/postgresql/data
      # This volume mounts the initialization script that creates the gym database
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - appnet

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - appnet
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - appnet

volumes:
  db-data:
  pgadmin:

networks:
  appnet:
    driver: bridge
