eureka:
  client:
    register-with-eureka: true

server:
  port: 8222

spring:
  application:
    name: gateway
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: members
          uri: lb://MEMBERS
          predicates:
            - Path=/api/v1/members/**
        - id: gyms
          uri: lb://GYM
          predicates:
            - Path=/api/v1/gyms/**
