server:
  port: 8222
  
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: members
          uri: http://localhost:8090/api/v1/members
          predicates:
            - Path=/api/v1/members/**
        - id: gyms
          uri: http://localhost:8070/api/v1/gyms
          predicates:
            - Path=/api/v1/gyms/**


eureka:
  client:
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0
